includes:
  - from_url:
      url: https://raw.githubusercontent.com/adamwalach/xgoreleaser/test-distroless/build.tmpl.yml

variables:
  brew_name: hydra
  brew_description: "The Ory OAuth2 and OpenID Connect Platform (Ory Hydra)"
  buildinfo_hash: "github.com/ory/hydra/v2/driver/config.Commit"
  buildinfo_tag: "github.com/ory/hydra/v2/driver/config.Version"
  buildinfo_date: "github.com/ory/hydra/v2/driver/config.Date"
  dockerfile: ".docker/Dockerfile-distroless"

project_name: hydra
